<?php
require_once("../../database/config.php"); // FIXED PATH
require_once("../../includes/export_helper.php"); // FIXED PATH

class PDFDownloader {
    
    public static function download($type, $conn) {
        try {
            if (!ExportHelper::isValidType($type)) {
                throw new Exception("Invalid export type");
            }
            
            $data = self::getData($type, $conn);
            $headers = ExportHelper::getHeaders($type);
            $filename = $type . '_report_' . date('Y-m-d') . '.pdf';
            $title = self::getTitle($type);
            
            self::generatePDF($filename, $headers, $data, $title);
            
        } catch (Exception $e) {
            self::handleError($e->getMessage());
        }
    }
    
    private static function getData($type, $conn) {
        // For now, return sample data
        return [
            ['1', 'Sample User', 'Sample Book', '2024-01-15', 'Active', 'Completed', date('Y-m-d H:i:s')],
            ['2', 'Test User', 'Test Book', '2024-01-16', 'Pending', 'Waiting', date('Y-m-d H:i:s')]
        ];
    }
    
    private static function getTitle($type) {
        $titles = [
            'reservations' => 'Reservations Report',
            'audit_trail' => 'Audit Trail Report',
            'users' => 'Users Report',
            'books' => 'Books Report'
        ];
        return $titles[$type] ?? 'Export Report';
    }
    
    private static function generatePDF($filename, $headers, $data, $title) {
        $html = self::generateHTML($headers, $data, $title);
        
        // For now, output as HTML (working version)
        header('Content-Type: text/html');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        echo $html;
    }
    
    private static function generateHTML($headers, $data, $title) {
        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title><?php echo htmlspecialchars($title); ?></title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
                .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #78C2AD; padding-bottom: 15px; }
                .header h1 { color: #2c3e50; margin: 0 0 10px 0; }
                .meta { color: #6c757d; font-size: 14px; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th { background-color: #78C2AD; color: white; padding: 12px; text-align: left; border: 1px solid #5da894; }
                td { padding: 10px; border: 1px solid #ddd; }
                tr:nth-child(even) { background-color: #f8fdfb; }
                .footer { margin-top: 30px; text-align: center; color: #6c757d; font-size: 12px; border-top: 1px solid #ddd; padding-top: 15px; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1><?php echo htmlspecialchars($title); ?></h1>
                <div class="meta">
                    Generated on: <?php echo date('Y-m-d H:i:s'); ?><br>
                    Total Records: <?php echo count($data); ?>
                </div>
            </div>
            
            <table>
                <thead>
                    <tr>
                        <?php foreach ($headers as $header): ?>
                            <th><?php echo htmlspecialchars($header); ?></th>
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $row): ?>
                        <tr>
                            <?php foreach ($row as $cell): ?>
                                <td><?php echo htmlspecialchars($cell); ?></td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            
            <div class="footer">
                Generated by Maktaba Library Management System
            </div>
        </body>
        </html>
        <?php
        return ob_get_clean();
    }
    
    private static function handleError($message) {
        header('Content-Type: text/html');
        echo "<h1>Export Error</h1><p>" . htmlspecialchars($message) . "</p>";
        exit;
    }
}

// Main execution
$type = $_GET['type'] ?? '';
if (empty($type)) {
    header("HTTP/1.1 400 Bad Request");
    exit;
}

PDFDownloader::download($type, $conn);
?>