<?php
require_once("../../includes/session_check.php");
require_once("../../includes/admin_check.php");
require_once("../../includes/report_helper.php");
require_once("../../database/config.php");

// Define getRecentReports if not already defined
if (!function_exists('getRecentReports')) {
  function getRecentReports($conn) {
    $sql = "SELECT report_id, generated_date, report_type, generated_by, status FROM reports ORDER BY generated_date DESC LIMIT 10";
    $result = $conn->query($sql);
    $reports = [];
    if ($result && $result->num_rows > 0) {
      while ($row = $result->fetch_assoc()) {
        $reports[] = $row;
      }
    }
    return $reports;
  }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Reports Engine | Maktaba Admin</title>
  <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/minty/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<?php include("../../includes/admin_nav.php"); ?>

<main class="container my-4">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h3 class="fw-bold text-success"><i class="bi bi-file-earmark-bar-graph"></i> Custom Report Generator</h3>
  </div>

  <form method="GET" action="../../api/export_api.php">
    <div class="row g-3 mb-4">
      <div class="col-md-4">
        <label class="form-label">Report Type</label>
        <select class="form-select" name="type" required>
          <option value="sales_report">Sales Report</option>
          <option value="orders_report">Orders Report</option>
          <option value="users_report">User Activity Report</option>
          <option value="books_report">Book Performance Report</option>
        </select>
      </div>

      <div class="col-md-3">
        <label class="form-label">Start Date</label>
        <input type="date" class="form-control" name="start_date" required>
      </div>

      <div class="col-md-3">
        <label class="form-label">End Date</label>
        <input type="date" class="form-control" name="end_date" required>
      </div>

      <div class="col-md-2 d-flex align-items-end">
        <button type="submit" class="btn btn-success w-100"><i class="bi bi-gear"></i> Generate</button>
      </div>
    </div>
  </form>

  <hr>

  <h5 class="fw-bold text-muted mb-3">📈 Recent Reports</h5>
  <table class="table table-striped table-hover">
    <thead class="table-primary">
      <tr>
        <th>Date</th>
        <th>Report Type</th>
        <th>Generated By</th>
        <th>Status</th>
        <th>Download</th>
      </tr>
    </thead>
    <tbody>
      <?php
        $reports = getRecentReports($conn);
        foreach ($reports as $r) {
          echo "
          <tr>
            <td>{$r['generated_date']}</td>
            <td>{$r['report_type']}</td>
            <td>{$r['generated_by']}</td>
            <td><span class='badge bg-success'>{$r['status']}</span></td>
            <td>
              <a href='../../api/export_api.php?report_id={$r['report_id']}' class='btn btn-sm btn-outline-primary'>
                <i class='bi bi-download'></i> Download
              </a>
            </td>
          </tr>";
        }
      ?>
    </tbody>
  </table>
</main>

</body>
</html>
