<?php
// modules/admin/working_export.php
// SIMPLE WORKING EXPORT - NO ERRORS

$type = $_GET['type'] ?? 'test';
$format = $_GET['format'] ?? 'excel';

// Sample data for different report types
$sampleData = [
    'reservations' => [
        ['Reservation ID', 'User', 'Book Title', 'Pickup Date', 'Status', 'Payment Status'],
        ['R001', 'John Doe', 'Introduction to PHP', '2024-01-15', 'Active', 'Paid'],
        ['R002', 'Jane Smith', 'Advanced Web Development', '2024-01-16', 'Pending', 'Unpaid'],
        ['R003', 'Mike Johnson', 'Database Design', '2024-01-17', 'Completed', 'Paid']
    ],
    'audit_trail' => [
        ['Log ID', 'User ID', 'Action', 'Description', 'IP Address', 'Timestamp'],
        ['A001', 'U001', 'LOGIN', 'User logged in', '192.168.1.100', '2024-01-15 10:30:00'],
        ['A002', 'U002', 'LOGOUT', 'User logged out', '192.168.1.101', '2024-01-15 11:15:00'],
        ['A003', 'U003', 'UPDATE', 'Profile updated', '192.168.1.102', '2024-01-15 14:20:00']
    ],
    'users' => [
        ['User ID', 'Username', 'Full Name', 'Email', 'Role', 'Status'],
        ['U001', 'john_doe', 'John Doe', 'john@email.com', 'Member', 'Active'],
        ['U002', 'jane_smith', 'Jane Smith', 'jane@email.com', 'Admin', 'Active'],
        ['U003', 'mike_j', 'Mike Johnson', 'mike@email.com', 'Member', 'Inactive']
    ],
    'books' => [
        ['Book ID', 'Title', 'Author', 'ISBN', 'Category', 'Status'],
        ['B001', 'Introduction to PHP', 'John Author', '978-1234567890', 'Programming', 'Available'],
        ['B002', 'Web Development', 'Jane Writer', '978-0987654321', 'Technology', 'Borrowed'],
        ['B003', 'Database Design', 'Mike Expert', '978-1122334455', 'Computer Science', 'Available']
    ],
    'test' => [
        ['ID', 'Name', 'Description', 'Date', 'Status'],
        ['1', 'Test Record 1', 'Sample data for testing', '2024-01-15', 'Active'],
        ['2', 'Test Record 2', 'Another test record', '2024-01-16', 'Completed']
    ]
];

// Get data for the requested type or use test data
$data = $sampleData[$type] ?? $sampleData['test'];

if ($format === 'pdf') {
    // Simple HTML "PDF"
    header('Content-Type: text/html');
    header('Content-Disposition: attachment; filename="' . $type . '_report.html"');
    
    echo "<html><head><title>" . htmlspecialchars($type) . " Report</title></head><body>";
    echo "<h1>" . htmlspecialchars(ucfirst($type)) . " Report</h1>";
    echo "<p>Generated: " . date('Y-m-d H:i:s') . "</p>";
    echo "<table border='1' style='width:100%; border-collapse:collapse;'>";
    
    foreach ($data as $row) {
        echo "<tr>";
        foreach ($row as $cell) {
            echo "<td style='padding:8px; border:1px solid #ccc;'>" . htmlspecialchars($cell) . "</td>";
        }
        echo "</tr>";
    }
    
    echo "</table>";
    echo "<p><em>Generated by Maktaba Library System</em></p>";
    echo "</body></html>";
} else {
    // CSV Export
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $type . '_report.csv"');
    
    $output = fopen('php://output', 'w');
    foreach ($data as $row) {
        fputcsv($output, $row);
    }
    fclose($output);
}
?>