<?php
// includes/pdf_generator.php
// Simple PDF Generator for Maktaba System

// Check if TCPDF is available, otherwise use simple HTML fallback
if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
}

if (!function_exists('generatePDF')) {
    /**
     * Generate and stream a PDF from HTML
     */
    function generatePDF($html, $filename) {
        try {
            // Try to use TCPDF if available
            if (class_exists('TCPDF')) {
                $pdf = new TCPDF();
                $pdf->SetCreator('Maktaba Admin');
                $pdf->SetAuthor('Maktaba');
                $pdf->SetTitle($filename);
                $pdf->SetMargins(10, 10, 10);
                $pdf->AddPage();
                $pdf->writeHTML($html, true, false, true, false, '');
                $pdf->Output($filename, 'D');
                return true;
            } else {
                // Fallback: output as HTML with PDF headers
                header('Content-Type: application/pdf');
                header('Content-Disposition: attachment; filename="' . $filename . '"');
                echo $html;
                return true;
            }
        } catch (Exception $e) {
            error_log("PDF generation error: " . $e->getMessage());
            return false;
        }
    }
}

/**
 * Simple PDF generation without TCPDF dependency
 */
function generateSimplePDF($headers, $data, $title, $filename) {
    $html = generatePDFHTML($headers, $data, $title);
    
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-cache, must-revalidate');
    
    echo $html;
    exit;
}

/**
 * Generate HTML for PDF
 */
function generatePDFHTML($headers, $data, $title) {
    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title><?php echo htmlspecialchars($title); ?></title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #78C2AD; padding-bottom: 15px; }
            .header h1 { color: #2c3e50; margin: 0 0 10px 0; }
            .meta { color: #6c757d; font-size: 14px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background-color: #78C2AD; color: white; padding: 12px; text-align: left; border: 1px solid #5da894; }
            td { padding: 10px; border: 1px solid #ddd; }
            tr:nth-child(even) { background-color: #f8fdfb; }
            .footer { margin-top: 30px; text-align: center; color: #6c757d; font-size: 12px; border-top: 1px solid #ddd; padding-top: 15px; }
            .no-data { text-align: center; padding: 40px; color: #6c757d; font-style: italic; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1><?php echo htmlspecialchars($title); ?></h1>
            <div class="meta">
                Generated on: <?php echo date('Y-m-d H:i:s'); ?><br>
                Total Records: <?php echo count($data); ?>
            </div>
        </div>
        
        <?php if (!empty($data)): ?>
        <table>
            <thead>
                <tr>
                    <?php foreach ($headers as $header): ?>
                        <th><?php echo htmlspecialchars($header); ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data as $row): ?>
                    <tr>
                        <?php foreach ($row as $cell): ?>
                            <td><?php echo htmlspecialchars($cell); ?></td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php else: ?>
            <div class="no-data">No data available for export</div>
        <?php endif; ?>
        
        <div class="footer">
            Generated by Maktaba Library Management System
        </div>
    </body>
    </html>
    <?php
    return ob_get_clean();
}
?>